import {User} from '../models/user.model';

export const mockUsers: User[] = [
  {id: "1", username: "Arash", password: "12345", email: "arash@gmail.com", role: "user"},
  {id: "2", username: "Sara", password: "12345", email: "sara@gmail.com", role: "admin"},
  {id: "3", username: "Ali", password: "12345", email: "ali@gmail.com", role: "sysAdmin"},
  {id: "4", username: "Neda", password: "12345", email: "neda@gmail.com", role: "user"},
  {id: "5", username: "Omid", password: "12345", email: "omid@gmail.com", role: "user"},
  {id: "6", username: "Lara", password: "12345", email: "lara@gmail.com", role: "admin"},
  {id: "7", username: "Reza", password: "12345", email: "reza@gmail.com", role: "user"},
  {id: "8", username: "Mina", password: "12345", email: "mina@gmail.com", role: "user"},
  {id: "9", username: "Kia", password: "12345", email: "kia@gmail.com", role: "user"},
  {id: "10", username: "Leila", password: "12345", email: "leila@gmail.com", role: "sysAdmin"},
  {id: "11", username: "Sina", password: "12345", email: "sina@gmail.com", role: "user"},
  {id: "12", username: "Tara", password: "12345", email: "tara@gmail.com", role: "user"},
  {id: "13", username: "Hamed", password: "12345", email: "hamed@gmail.com", role: "admin"},
  {id: "14", username: "Shiva", password: "12345", email: "shiva@gmail.com", role: "user"},
  {id: "15", username: "Navid", password: "12345", email: "navid@gmail.com", role: "user"},
  {id: "16", username: "Yasmin", password: "12345", email: "yasmin@gmail.com", role: "sysAdmin"},
  {id: "17", username: "Farhad", password: "12345", email: "farhad@gmail.com", role: "user"},
  {id: "18", username: "Elahe", password: "12345", email: "elahe@gmail.com", role: "user"},
  {id: "19", username: "Kourosh", password: "12345", email: "kourosh@gmail.com", role: "user"},
  {id: "20", username: "Nima", password: "12345", email: "nima@gmail.com", role: "user"},
  {id: "21", username: "Sahar", password: "12345", email: "sahar@gmail.com", role: "admin"},
  {id: "22", username: "Pouya", password: "12345", email: "pouya@gmail.com", role: "user"},
  {id: "23", username: "Mitra", password: "12345", email: "mitra@gmail.com", role: "user"},
  {id: "24", username: "Shahram", password: "12345", email: "shahram@gmail.com", role: "sysAdmin"},
  {id: "25", username: "Negin", password: "12345", email: "negin@gmail.com", role: "user"},
  {id: "26", username: "Aria", password: "12345", email: "aria@gmail.com", role: "user"},
  {id: "27", username: "Ladan", password: "12345", email: "ladan@gmail.com", role: "user"},
];
